### ISSUE TITLE
Tag a v1.0.0 release

### ISSUE THREAD

**Issue by rmm5t** [nicknovitski/rbenv-gem-update#1]
Would you mind adding a `v1.0.0` tag to this repo? I'd like to submit this plugin as a new formula to Homebrew and an official release will help with that. 

```
git tag v1.0.0
git push --tags
```

**Comment by nicknovitski** [comment]
It would be reasonable for you to have forgotten about this by now, but either way, I've created a `v1.0.0` tag. :smile:
